Created AccommodationController.
brblnt/webprojekt pull request #12
Opened 2023-04-29 20:09 UTC by zoltannegyesi

2023-04-29 20:10 UTC, zoltannegyesi commented
Megcsináltam neked az update logikát is rá, hogy én hogy csinálnám meg, majd átalakítod, ahogy szeretnéd.

Ja meg majd ezt ne mergeld, majd rebaselem, mielőtt bekerülne.

2023-05-04 17:14 UTC, brblnt commented
akkor majd még várom h rebaseld

2023-05-04 17:34 UTC, brblnt requested changes

2023-05-04 17:34 UTC, brblnt commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/controller/AccommodationController.java
> +    public ResponseEntity<AccommodationDTO> update(final @PathVariable("id") Long id, @RequestBody AccommodationDTO accommodationDTO) throws NotFoundException {
nem kéne külön model a web rétegbe?

2023-05-04 17:34 UTC, brblnt commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/service/service/impl/AccommodationServiceImpl.java
> +  public AccommodationDTO update(AccommodationDTO oldAccommodation, AccommodationDTO newAccommodation) {
ezt majd kicsit átalakítottam de ua maradt a lényegi része

2023-05-04 17:34 UTC, brblnt commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/controller/AccommodationController.java
> +        final AccommodationDTO oldAccommodation = accommodationService.getById(id);
ezt majd szerviz rétegben lekérdezem marad az egy paraméteres

2023-05-04 17:38 UTC, zoltannegyesi commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/controller/AccommodationController.java
> +    public ResponseEntity<AccommodationDTO> update(final @PathVariable("id") Long id, @RequestBody AccommodationDTO accommodationDTO) throws NotFoundException {
a dto osztályok ezért lettek létrehozva
hogy olyan formátumban legyenek a mezők, amiket meg tud kapni a frontendtől.

2023-05-04 17:38 UTC, zoltannegyesi commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/controller/AccommodationController.java
> +    public ResponseEntity<AccommodationDTO> update(final @PathVariable("id") Long id, @RequestBody AccommodationDTO accommodationDTO) throws NotFoundException {
egyébként szerintem meg úgy kéne, hogy a service réteg nem dolgozik egyáltalán már a dtokkal, hanem csak a controller réteg. 
szerintem a service-nek már az entitás osztályokkal kéne dolgoznia

2023-05-04 17:39 UTC, brblnt commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/controller/AccommodationController.java
> +    public ResponseEntity<AccommodationDTO> update(final @PathVariable("id") Long id, @RequestBody AccommodationDTO accommodationDTO) throws NotFoundException {
viszont van a request és response rész

2023-05-04 18:17 UTC, brblnt approved these changes

2023-05-04 18:17 UTC, merged