fix
brblnt/webprojekt pull request #45
Opened 2023-05-28 19:15 UTC by brblnt

2023-05-28 19:53 UTC, zoltannegyesi requested changes

2023-05-28 19:53 UTC, zoltannegyesi commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/data/repository/AccommodationRepository.java
> +  List<Accommodation> findAllByAuthID(Long authenticationId);
ezt próbáltad már?
szerintem csak úgy fog működni, ha az a neve: findAllByAuthenticationId
a jpa elég szigorú erre.

2023-05-28 19:53 UTC, zoltannegyesi commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/data/repository/BookingRepository.java
> +  List<Booking> findAllByUserID(Long userId);
itt is lehet, hogy az D-nek kicsinek kell lennie

2023-05-28 19:53 UTC, zoltannegyesi commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/data/repository/BookingRepository.java
> +
itt is

2023-05-29 16:48 UTC, zoltannegyesi requested changes

2023-05-29 16:48 UTC, zoltannegyesi commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/data/entity/AuthenticationData.java
> +  @Column(name = "user_name", nullable = false, unique = true)
benne maradhat a unique, sőt nem is baj, hogy itt van, de amúgy is már a regisztráció validációnál csak egyet enged tovább.

2023-05-29 16:48 UTC, zoltannegyesi commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/data/repository/ApplicationUserRepository.java
> +  Optional<ApplicationUser> findApplicationUserByAuthenticationId(Long authenticationId);
findByAuthenticationId

2023-05-29 17:32 UTC, brblnt commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/data/entity/AuthenticationData.java
> +  @Column(name = "user_name", nullable = false, unique = true)
nem volt jó mivel @kristofvad  tudott ugyanolyan névvel kettőt létrehozni

2023-05-29 17:33 UTC, zoltannegyesi commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/data/entity/AuthenticationData.java
> +  @Column(name = "user_name", nullable = false, unique = true)
@kristofvad a developot használta, vagy a main-et? :)

2023-05-29 17:33 UTC, zoltannegyesi commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/data/entity/AuthenticationData.java
> +  @Column(name = "user_name", nullable = false, unique = true)
a kettő nem ugyanott tart

2023-05-29 17:34 UTC, zoltannegyesi approved these changes

2023-05-29 17:35 UTC, brblnt commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/data/entity/AuthenticationData.java
> +  @Column(name = "user_name", nullable = false, unique = true)
hat akkor lehet már orvosolva lett de attól el nem rontja az unique

2023-05-29 17:36 UTC, merged