Create more service and little changes
brblnt/webprojekt pull request #8
Opened 2023-04-19 12:57 UTC by brblnt

- add more service class
- fixes

2023-04-19 14:39 UTC, zoltannegyesi requested changes
Néhány dolog, de jó.

2023-04-19 14:39 UTC, zoltannegyesi commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/service/converter/ConvertApplicationUserEntityToDTO.java
> +  private final AuthenticationUtilities authenticationUtilities;
ide nem kell egy autowired? vagy az újabb springbe már azok se kellenek?

2023-04-19 14:39 UTC, zoltannegyesi commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/service/converter/ConvertBookingEntityToDTO.java
> +      throw new RuntimeException(e);
amúgy ezeket az exceptionoket ki lehetne logolni

2023-04-19 14:39 UTC, zoltannegyesi commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/service/converter/ConvertApplicationUserEntityToDTO.java
> +      throw new RuntimeException(e);
itt is lehetne logolni

2023-04-19 14:39 UTC, zoltannegyesi commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/service/service/BookingService.java
> +  boolean delete(Long id);
Boolean

2023-04-19 14:39 UTC, zoltannegyesi commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/service/service/impl/AccommodationServiceImpl.java
> +    } catch (Exception e) { // TODO: legyen konkrétabb exception?
esetleg lehet valami DeletionException, vagy valami hasonló

2023-04-19 14:39 UTC, zoltannegyesi commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/service/service/impl/ApplicationUserServiceImpl.java
> +    return null;
gondolom ezek még később lesznek implementálva

2023-04-19 14:39 UTC, zoltannegyesi commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/service/service/impl/BookingServiceImpl.java
> + */
amúgy majd az én részemen is megcsináljam a java docokat?

2023-04-19 14:39 UTC, zoltannegyesi commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/service/service/impl/BookingServiceImpl.java
> +  private final Converter<Booking, BookingDTO> convertBookingEntityToDTO;
erre nincs külön konverterünk?

2023-04-19 14:40 UTC, brblnt commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/service/service/impl/BookingServiceImpl.java
> +  private final Converter<Booking, BookingDTO> convertBookingEntityToDTO;
de van létrehozva

2023-04-19 14:41 UTC, brblnt commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/service/service/impl/BookingServiceImpl.java
> + */
csinálhatsz

2023-04-19 14:41 UTC, brblnt commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/service/service/impl/ApplicationUserServiceImpl.java
> +    return null;
igen

2023-04-19 14:42 UTC, zoltannegyesi commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/service/service/impl/BookingServiceImpl.java
> +  private final Converter<Booking, BookingDTO> convertBookingEntityToDTO;
akkor azt kénte itt haszálni típusnak szerintem

2023-04-19 14:42 UTC, brblnt commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/service/service/impl/AccommodationServiceImpl.java
> +    } catch (Exception e) { // TODO: legyen konkrétabb exception?
megnézésem a beépített fv milyen kivételt dob

2023-04-19 14:44 UTC, brblnt commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/service/service/impl/BookingServiceImpl.java
> +  private final Converter<Booking, BookingDTO> convertBookingEntityToDTO;
ilyenkor azt a konvertert használja csak ilyen formában lett behívva

2023-04-19 14:49 UTC, zoltannegyesi commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/service/service/impl/BookingServiceImpl.java
> +  private final Converter<Booking, BookingDTO> convertBookingEntityToDTO;
igen, azt haszálja, de szerintem az "olvasó" könnyebben tudja, hogy milyen converter ez. De mivel ezt a részt ketten hasznájuk, maradhat. Ez már csak esztétika

2023-04-24 13:25 UTC, zoltannegyesi requested changes
Ha ez kész, mehet be.

2023-04-24 13:25 UTC, zoltannegyesi commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/service/service/impl/AccommodationServiceImpl.java
> +      return false;
doksiban:

deleteById

Deletes the entity with the given id.
If the entity is not found in the persistence store it is silently ignored.

Parameters:
id - must not be null.
Throws:
[IllegalArgumentException] - in case the given id is null

Tehát akkor az IllegalArgumentException-t el lehetne kapni.

2023-04-24 13:25 UTC, zoltannegyesi commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/service/service/impl/ApplicationUserServiceImpl.java
> +      return false;
IllegalArgumentException

2023-04-24 13:25 UTC, zoltannegyesi commented on hotel-booking/src/main/java/nostra/cosa/hotelbooking/service/service/impl/BookingServiceImpl.java
> +      return false;
IllegalArgumentException

2023-04-24 13:32 UTC, merged